// Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

// By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

function solution(num) {
  let previous = 0;
  let current = 1;
  let sum = 0;
  let next;

  for (current; current <= num; ) {
    next = current + previous;
    previous = current;

    if (current % 2 !== 0) {
      sum += current;
    }

    current = next;
  }

  return sum;
}

console.log(solution(4000000));
